# Generated by Django 4.2.1 on 2023-05-23 14:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('created_at', models.TimeField(default=datetime.time(7, 30, 19, 85893))),
                ('completed_at', models.TimeField(blank=True, null=True)),
                ('to_do_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='to_do_app.todolist')),
            ],
        ),
    ]
